// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BLL.Models;

public partial class Game
{
    public Game() { }
    public int Id { get; set; }

    public string Title { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int PublisherId { get; set; }

    public DateTime ReleaseDate { get; set; }

    public virtual ICollection<GameDeveloper> GameDevelopers { get; set; } = new List<GameDeveloper>();

    public virtual ICollection<GameGenre> GameGenres { get; set; } = new List<GameGenre>();

    public virtual Publisher Publisher { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}