// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BLL.Models;

public partial class GameDeveloper
{
    public GameDeveloper() { }
    public int GameId { get; set; }

    public int DeveloperId { get; set; }

    public virtual Developer Developer { get; set; }

    public virtual Game Game { get; set; }
}