
INSERT INTO HyperplayRealmDB.dbo.Publisher (Name)
VALUES
('Ishbull Studios'),
('HONGKONG FEIFAN CO'),
('Moneer Marouf'),
('Defroids'),
('Method 9 Software'),
('Lamina Studios'),
('David Long'),
('SpookyAction'),
('Hide Head'),
('Bandai Namco Entertainment'),
('The Game Bakers'),
('RockingDyde!'),
('CarloCGC'),
('Dr. Cyril Splutterworth'),
('Team Booky'),
('Guangzhou Dianjinshi Information Technology Co'),
('Dead Drop Studios'),
('MAYKEYS'),
('独资个人'),
('Gamer Girl'),
('All in! Games'),
('Sony Interactive Entertainment'),
('HAILFALLKOMPANY'),
('Sweety Cute Studio'),
('Stephen Damm Boeaas'),
('Modus Games'),
('Wacky Wallaby'),
('Oriol Gomez'),
('Pankabre'),
('Nukearts Studio, Wieden+Kennedy São Paulo'),
('Rubber cap studio'),
('Activision Blizzard'),
('Pinel Games'),
('Pathea Games'),
('Mzg Games'),
('FZ-Tech'),
('Hidden Depths Games'),
('Groove Studio'),
('Thomas Gervraud'),
('Spooky Doughnut Games'),
('3dm_live_wallpapers'),
('MARAEV GAMES'),
('Masquerade Games'),
('Brainium Studios'),
('Daniel patrick Cenneno'),
('BBP Publishing'),
('Enoops'),
('gamigo Publishing'),
('Phoenix'),
('Hong Kong Netease Interactive Entertainment'),
('MenZ Studio'),
('RatDog Games'),
('Nintendo'),
('Dexter.CO'),
('D-Tarrow'),
('双叶小组'),
('XXL'),
('Polaris(붙박이별)'),
('Tentworks Interactive'),
('Tamas Geller'),
('Ave Studio'),
('Learnings Co'),
('JunyJell'),
('Final Scene dev'),
('General Interactive Co.'),
('mountain bird'),
('TapNice'),
('Djamp Games'),
('Joma Rage'),
('Supergiant Games'),
('Famous Dogg Studios'),
('MoonlightGames'),
('SVGames'),
('FLERO GAMES Co.,Ltd.'),
('Fatbot Games'),
('Philozofia Studio'),
('remete'),
('Ercan Karabulut'),
('Simulated Entertainment'),
('VMS Media'),
('indiegames3000'),
('Sengkala Dev'),
('小龙 黄'),
('G5 Entertainment'),
('Microsoft Game Studios'),
('Loneminded'),
('Alexandru Marusac'),
('星罗云布Nebula Game Studio'),
('Kai Ruma Games'),
('Clouded Leopard Entertainment'),
('Sycoforge'),
('KillHouse Games'),
('Eclair Lab'),
('KAYAC'),
('Mordiem Entertainment'),
('Astragon Entertainment'),
('Bigben Interactive'),
('Atelier ATIC'),
('SimFabric'),
('Rita'),
('変態電子社'),
('Mirador Studio'),
('FI Gaming'),
('Summertime'),
('Fat Dog Games'),
('FRANK'),
('2Awesome Studio'),
('Huntah'),
('Steve Suetterlin'),
('Sinnera'),
('Ravenscourt'),
('Gionathan Pesaresi'),
('Phoenix Limit'),
('Kabelo Leboa'),
('Ariel Villafane'),
('Team Lucid Dream'),
('Crunchyroll Games'),
('Games 2rk'),
('xiangzhou zheng'),
('Laptop gamers'),
('The Dairymen'),
('Myshkin Entertainment'),
('Thi Thien Doan'),
('SmileBoy'),
('Keyue Studio'),
('MobArts'),
('Valorware'),
('iLand Studios'),
('Klick Ink L.P.'),
('Casus Belli Game and Animation Studios'),
('LuGus Studios'),
('Pixamo'),
('Modern Wolf'),
('Rain Games'),
('pencil'),
('Deeber'),
('notagamestudio'),
('Yaza Games'),
('Rocketship Park'),
('Atlus'),
('Meta Games'),
('Accolade'),
('machineboy'),
('Axoma Games'),
('DANGEN Entertainment'),
('GosuGames'),
('Bombreature Games'),
('Linked Squad'),
('SpinAttack Studio'),
('Jose Luis Escobar'),
('Alexander Salcedo'),
('AMDI Studios'),
('Wearevragency'),
('CD PROJEKT RED'),
('CLASSWIRE'),
('BadLand Publishing'),
('Bad Vices Games'),
('Shaggy Dwarf'),
('Team Dogpit'),
('Lion Studios'),
('YDKR'),
('Daedalic Entertainment'),
('THAI HOA TECHNOLOGY AND MEDIA SOLUTION JOINT STOCK COMPANY'),
('Post Boredom Games'),
('COLORFUL TAILS'),
('Light Fox Games'),
('Kongregate'),
('Fantastico Studio'),
('Mancheolsoft'),
('DreamFly Games'),
('Black Tabby Games'),
('Lsq Entertainment'),
('Koch Media'),
('Beep Yeah'),
('Yuling Li'),
('KING Art Games'),
('Aineko Games'),
('SuperPrism Technology Co'),
('gelare1029745'),
('The Wandering Band'),
('Kwalee'),
('Homunculus Games'),
('Pazu Games'),
('Ibis Games'),
('Grade 9 Games'),
('M58'),
('Infinite8'),
('Dgelioncel'),
('Charm Games'),
('DSGame'),
('TSUKASA MIZUI'),
('1C Entertainment'),
('Think Yeah'),
('Green Forest Games'),
('Limitless Imagination'),
('Kamit Games'),
('Octavi Navarro'),
('LIFETO'),
('Ubisoft Entertainment'),
('MEDFUT, OOO'),
('North of Earth'),
('Punion Game Studio'),
('Conor Davis'),
('ANFWorks'),
('firepillar2'),
('TheWingedBlue'),
('GreenSoft'),
('TheRealBigMushroom'),
('Tom Wiggins'),
('Boom Games'),
('Ketchapp'),
('Nadeem Munawar'),
('Snapbreak Games'),
('Aspyr'),
('CAREBOT GAMES'),
('Square Enix'),
('Endless Ritual Assembly'),
('Bloober Team'),
('Skalden'),
('KUMA SOFT'),
('HornyGames'),
('Derya Agiroglu'),
('Spooky House Studios UG haftungsbeschraenkt'),
('Narayana Walters'),
('by fraimone'),
('Split Light Studio'),
('Rocket Tech'),
('Paradox Interactive'),
('borgia mango art'),
('TC Games'),
('Zoo'),
('Potata Company'),
('KPL'),
('Roger Kaffer'),
('Kedexa'),
('可可西工作室'),
('White Keyframe'),
('Big Bird Games'),
('MyACG Studio'),
('To Luan Bui'),
('Milestone'),
('Lezy Bee'),
('Paulo Henrique Franqueira'),
('LUCKY GO STUDIO'),
('GuMa Games'),
('VIZOR APPS'),
('Rosyaev'),
('PlayPlayGame'),
('Steel Peak Games'),
('Feelingtouch'),
('PlayWay'),
('Hi-Rez Studios'),
('Amagumo Horn'),
('Church of Bolloxology'),
('Loony Code'),
('VR-HERE'),
('RoadToIndieGameDev'),
('Giant Gourami'),
('天威传说'),
('Kadir Sert'),
('IFIDEV'),
('Rusty Lake'),
('Foxy Boxy Games'),
('Bytecat Games'),
('郑州百易科技有限公司'),
('Nacks Soft'),
('Underbite Games'),
('-In.'),
('Night Dive Studios'),
('BibaDev'),
('Hammer&Ravens'),
('Bernhard Potuzak'),
('The Worst of Friends'),
('Fasold Games'),
('Hayden'),
('Anna Nikolaevna'),
('laith dawoud'),
('IEC CANADA HOLDINGS'),
('CLICKTEAM L.L.C.'),
('大きくて強い'),
('FutureGame'),
('Stratton Studios'),
('Serafim Katasonov'),
('Kadir Danisman'),
('Geostegma'),
('Draw Distance'),
('PrismMedia'),
('Štěpán Meister'),
('Ammonite Design Studios'),
('Orfeas Game Studio'),
('Foxydudestudios'),
('Matt Barth'),
('Colton Boyd'),
('Chatteract'),
('Virede'),
('Nexcore Studios'),
('Platonic Games'),
('DreamPipe'),
('Yasei no koubou'),
('匠门电子科技有限公司'),
('Sisusieni'),
('Wolverine Studios'),
('BITKHED, OOO'),
('Marcin Priachin'),
('Piotr Şişcov'),
('Daniel Fornace'),
('University of Texas at Austin SAGA Lab'),
('GXPlay'),
('ChillFun'),
('Memory Card Game'),
('Kaikalii'),
('Mediacube Games'),
('Tomas Gomez'),
('Marvin Krueger'),
('Run and jump games'),
('BeautiFun Games'),
('DIEGO MEJIA'),
('guilemus'),
('The Big Studio'),
('YAW Studios'),
('Smart Gamma'),
('Blender Games'),
('Positech Games'),
('幻想理戈游戏开发工作室'),
('Queen Bee Games'),
('海貓'),
('Minsan'),
('Beijing Hydra Technology Co'),
('Waqudoo'),
('MAGame'),
('Celerium Games'),
('Alpheratz*'),
('Kumogami'),
('Floor 100'),
('Fablesoft Studios'),
('Andorf Games'),
('KN1053'),
('Sunday'),
('Alexander Westwater'),
('Chi Lea Tran'),
('OFF1C1AL'),
('Awaken Realms Digital'),
('StandArts'),
('Brace Yourself Games'),
('SquareBoxStudio'),
('Blue Phoenix Games'),
('Anton Kryukov'),
('SHAPE KEEPER CO'),
('KuKo'),
('Myth Entertainment'),
('VRillAR'),
('Álvaro García'),
('Tactical Adventures'),
('Sudakarn Vivatvanichkul'),
('Nicolas Peichel'),
('Phoenix Online Studios'),
('Sijawa Production'),
('C3B Games'),
('Softbear'),
('SmokeSomeFrogs'),
('seo jin baek'),
('BoomBit'),
('Side Group'),
('James Swiney'),
('Flashpoint Games'),
('Adam Rowe'),
('Michael Pandora'),
('Mateus Lima'),
('Gregory McAdory'),
('Xu Li'),
('Warner Bros. Interactive'),
('Piece Of Voxel'),
('Insexsity_team'),
('Winged Cloud'),
('Frictional Games'),
('Basic Sloth'),
('mafgames'),
('One Small Favor'),
('Gali from Hell'),
('trianglepixel'),
('Sekai Project'),
('Guin Entertainment'),
('DigiPen Institute of Technology'),
('LEMOON BILISIM YAZILIM REKLAM VE PAZARLAMA LIMITED SIRKETI'),
('Courtney Dawson'),
('Vimes Entertainment'),
('Axel Sonic'),
('KirleyGames'),
('SEGA'),
('Encore'),
('Banamurai Media'),
('JanduSoft'),
('Zerouno Games'),
('宁夏华夏西部影视城有限公司'),
('GTGD'),
('Miniclip'),
('TimeWastingGames'),
('Bryce Hochstedler'),
('Know All Studios'),
('Burnout Game Ventures'),
('Yacht Club Games'),
('Pixelbite'),
('Pedro Gilabert'),
('YUANWEIZHE'),
('Mundo Pilbo'),
('Kemal Kuzu'),
('EXTREMESOFT BILISIM REKLAMCILIK TICARET LIMITED SIRKETI'),
('Heatherglade Publishing'),
('GrabTheGames'),
('Tero Lunkka'),
('Timberline Studio'),
('修仙传'),
('Bungie'),
('Offworld Industries'),
('Smart Flix'),
('grin robot'),
('ADOG'),
('Sugar Bush Studios'),
('Rewind Games'),
('Indie Ninjas'),
('Fatbot Games, s. r. o.'),
('头号玩家'),
('Heartbit Interactive'),
('ShmoeSoft'),
('The Molasses Flood'),
('EnderWings'),
('Mediawork'),
('Self-Published'),
('Cloudred'),
('H.O SOFT'),
('Robert Barkow'),
('Cobble Games'),
('Dear Villagers'),
('Kijin Taisha'),
('Konnichiwa Games'),
('Gluten Free Games'),
('Oksana Bula'),
('Vox Studios'),
('Shining Lizards'),
('Yle Sandbox'),
('ViArt Studio'),
('A Small Game'),
('Headup Games'),
('Imperium Interactive Entertainment'),
('2DG Games'),
('Siddharth Sivaraman'),
('Javier Richi'),
('Proponent Games'),
('Xavi Heras'),
('Portaalin Pojat Oy'),
('David M.'),
('caves rd'),
('Tly'),
('Red Skald'),
('VBG'),
('cookapps'),
('Capcom'),
('Walkabout'),
('K App.'),
('Ginkgo Studio'),
('Helix Games'),
('ROOT 76'),
('Buka Entertainment'),
('Glitch Studio'),
('99 Dragons'),
('Sixpi Developers'),
('Limited Games'),
('Deer Dream Studios'),
('AlphaGarg'),
('OrionSoft'),
('D-Ark Studio'),
('Dagestan Technology'),
('Tyler F Smith'),
('Aksys Games'),
('Romulus'),
('Blackthornprod'),
('GAGEX Co.,Ltd.'),
('Scream In To Void'),
('尼古拉丝工房Nicolas'' Works'),
('Gutter Arcade'),
('RhinoGearz'),
('Musa GUNGOR'),
('Pena'),
('FastRam Design'),
('Barty Games'),
('ComonGames OOO'),
('The Scholastics'),
('Dream Nerdy'),
('Jérôme Braëms'),
('Lunar Madcap'),
('alili'),
('Kozhakov'),
('miHoYo'),
('Haywire Game Studios'),
('Na Xiao'),
('Eugene Volos'),
('Dance Lisa Dance'),
('DELAPAIX'),
('ChangeMe'),
('Rule Weaver'),
('Oculus Studios'),
('Seize Studios'),
('Siberian Mouse'),
('Renegade Sector Games'),
('Hibiki Yano'),
('Considra Games'),
('kitsada gowitwanit'),
('Major Games'),
('Dejobaan Games'),
('2 Barrel Arts'),
('Q-Games'),
('VAVEDA GEIMZ, OOO'),
('Valkyrie Initiative'),
('Kubold'),
('PartTimeIndie'),
('Trump''s House'),
('Saber Studios'),
('Young Horses'),
('Bethesda Softworks'),
('RoomsforRockets'),
('Iván Marcelo Pretti'),
('LouveSystems'),
('Dire Wolf Digital'),
('Auggo Doggo Games'),
('Y Press Games'),
('Analog Joker'),
('Nova''s Army'),
('Spaceflower'),
('White Box'),
('META Publishing'),
('AT'),
('Iceberg Interactive'),
('Fireapples'),
('Matrioshka Games'),
('Ratloop Games Canada'),
('Pham Studio'),
('ISHIN-DENSHIN GAMES'),
('Bytro Labs'),
('Creative Storm Entertainment'),
('Cellar Vault Games'),
('Eternal Lighthouse'),
('Oddworld Inhabitants'),
('CHILL & PLAY'),
('GoodZeit UG'),
('Maksym Chepurnyi'),
('WanadevStudio'),
('Kaisouroku Games'),
('Rollic Games Oyun Yazilim ve Pazarlama Anonim Sirketi'),
('Beautiful Glitch'),
('Coatsink'),
('zAwA'),
('Wixot'),
('Cube Software'),
('Letiman Games'),
('Enjoy the Tale'),
('OG Oliver Games'),
('Makrogames'),
('Xian Diankou Software Technology Co'),
('2GenPro'),
('Kai Melton'),
('Cui Wenping'),
('血色双眸'),
('KX Games'),
('Arnold Rauers'),
('Guangzhou Bepic InfoTech'),
('No Gravity Games'),
('电钮组'),
('Substance Games'),
('Jan Jileček'),
('Rabotiagi games'),
('NPMS(Number Personal Model Studio)'),
('Kagura Games'),
('Com2uS'),
('Little Ricebowl'),
('Fourhorn Games'),
('BreakAway'),
('RealityArts Studio'),
('玫瑰工作室'),
('Eivind Magnus Noersterud Hvidevold'),
('ARTE France Apps'),
('Prothos'),
('Gumi'),
('CarX Technologies'),
('Galactic Spire'),
('Milky Tea Studios'),
('Asephy'),
('Longwind Studio'),
('Teorldegames'),
('Microids'),
('岗成年'),
('PaulArt'),
('G1 Playground'),
('Pham Anh'),
('Ling Games'),
('Liam Clift'),
('Tim Melnikov'),
('Gbanga'),
('MUJOY PTE'),
('Odders Lab'),
('Gamonster'),
('Raw Fury'),
('REMIMORY'),
('GexagonVR'),
('PLAYWAY SPOLKA AKCYJNA'),
('Bitbeast Games'),
('SakuraGame'),
('MVGames'),
('Frontier Foundry'),
('Brinemedia'),
('Nanjing Dingzun Network Development'),
('Boutaina Araho'),
('Kokutou Umeboshi'),
('Enrico Carrano'),
('认真玩工作室'),
('207 Studios'),
('Comic and Sons'),
('Parange Project'),
('SimDevs'),
('Chameleon Games'),
('Josh Games'),
('Wild River Games'),
('Eroducate'),
('October Night Games'),
('PQube'),
('Fantastic Turbine'),
('Funny i Games'),
('Gaël Bourhis'),
('JD Video Game Productions'),
('Rosa Special Studio'),
('Rivstyx Games Studio'),
('MyDreamForever_Old'),
('Kimberly Mugler'),
('Bandai'),
('Zanardi and Liza'),
('ANDREI MURASHKEVICH'),
('Marvelous'),
('Imperian Online'),
('The Overall Angle'),
('Tao Pan'),
('NGV Studio'),
('Annapurna Interactive'),
('ÖBB/TopGames'),
('Idea Factory'),
('Icy Studios'),
('Yso Corp'),
('Hoodust Enterprises'),
('Hentai Key'),
('@unepic_fran'),
('ZPFGAME'),
('Onemobi'),
('宇豪 蔡'),
('Officeu Co'),
('Troyar'),
('The Socially Awkward Studio'),
('FridolinSlehacka'),
('EYEWIND LIMITED.'),
('Draydur Studio'),
('Lowtek Games'),
('Meerkat Codes'),
('Thomas Van Bouwel'),
('Frontier Developments'),
('Hero Games'),
('Elasto Mania Team'),
('Arcadia'),
('Papas con Mojo Games'),
('Thundermagnet'),
('DigiMight'),
('Virtual Arts Studio'),
('Mens Sana Interactive'),
('Destructive Creations'),
('somdy age'),
('Muhammad Salman Malik'),
('En Widunderlig Produktion'),
('Smash The Code'),
('Redkar'),
('Ratalaika Games'),
('See You'),
('ComputerDev'),
('Crisan Andrei Alexandru'),
('Zai Studio'),
('The Last Developer'),
('Fire Game Studios'),
('Easy Mode'),
('ALEKSPLEI, OOO'),
('Onlumi.dev'),
('NIS America'),
('DAN SU'),
('Snapshot Games'),
('Mujo Games'),
('Source Byte'),
('Invoke Games'),
('Maksym Dzitsiuk'),
('Cute Squirrel Studios'),
('ERY VFX'),
('Ein Prozent e.V.'),
('Sons of welder'),
('A3D Studio'),
('Paradox White Cat'),
('Unexpected'),
('Juvty Worlds'),
('TeamTinyCrack'),
('Zeruk Studios'),
('Mehsoft'),
('Marius Elvert'),
('Grey Alien Games'),
('NVLMaker'),
('Michael A. Rivera'),
('Techpack'),
('OXO Games'),
('MoonGame'),
('MollyAvast'),
('s. r. o.'),
('RedLizard Studio'),
('Group of Brothers Yazilim Sistemleri Anonim Sirketi'),
('Winterlook Games'),
('Lemondo Games'),
('Haruneko Entertainment'),
('Arkhouse Telegnosis'),
('Liam Hanrahan'),
('Pulsarnik Productions'),
('SorceressGameLab'),
('Sergey Mezhakov'),
('Looking for publish/Invest'),
('Blue Collar Games'),
('Pharos Fables'),
('Starni Games'),
('天局'),
('Marcelo Barbosa'),
('Zio'),
('PTW'),
('Carlos Arturo Rodriguez Silva'),
('DavidPixel'),
('Your GG Project'),
('ICAD/VisionLab PUC-Rio'),
('Christoph Meister'),
('BERRY Games'),
('Suzannah Loughran'),
('TheBeamerLLC'),
('Eggcode'),
('Aaron Hibberd'),
('Future Friends Games'),
('A & D Cooperation'),
('ZOMBIESTD'),
('M9 Packaging'),
('Kaverini Korp'),
('Slitherine'),
('Friendly Fire Studios'),
('Graffiti Games'),
('SoerGame'),
('Gaming Factory'),
('Team Meat'),
('WildSphere'),
('Solid Water Studios'),
('Legacy Game Studio'),
('铿 杨'),
('EGAMER'),
('真龙传世'),
('Yiming'),
('Maciej Dabrowski'),
('Roach Game Studio'),
('Acme perfect'),
('Hyun-joong Kim'),
('Pangolin Park'),
('Avisgames'),
('First Coffee'),
('Fluffy Bunny Studios'),
('Cherry Kiss Games'),
('Humble Bundle'),
('유진게임즈'),
('Perchang'),
('Hiruko Time App'),
('Wales Interactive'),
('SnowCube I/S'),
('Laush Studio'),
('DigiPlox'),
('Sinn Studio'),
('HONGKONG 707 INTERACTIVE TECHNOLOGY CO'),
('Bubblegum Games'),
('Old Eagle'),
('Man Changing Ideas'),
('Lovely Warriors of Friendship'),
('Strelka Games'),
('Capsule Core'),
('Wrkwrk'),
('Vita Games'),
('Stegalosaurus Game Development'),
('Zeta bit'),
('SEKTOR GAMES'),
('Frozenbyte'),
('Jane Titor'),
('Merge Games'),
('PANORAMIK GAMES'),
('Garage Digital'),
('SuperPlanet'),
('Xonomy'),
('Beijing Lecheng Ruixiang Technology Co'),
('Quyet Ngo'),
('ClÃ©ment Salotti'),
('MoniusProductions'),
('Blackflag Games'),
('LOOKSTEN'),
('Polycat Studios'),
('Nacho Alfonso Brito'),
('GAME Games'),
('Sic''em Studios'),
('Gaming at Work'),
('Babil Games'),
('MJMac'),
('RoseWater Studios'),
('Rayark International'),
('Fellow Traveller'),
('Tom Domenico'),
('BaM Media'),
('ThatBoopGuy'),
('DJ Close'),
('2S Games'),
('Juraj Husek Game Studio'),
('Beach Day Studios'),
('XSEED Games'),
('Faxdoc and nostalgiatree games'),
('EpiXR Games'),
('Bit2Good Ug'),
('Ninetap'),
('道华 陈'),
('Four Pixels Games'),
('Squid Related Games'),
('Pen in Apple studio'),
('GEOMETRIC BYTES'),
('X3M Games'),
('William Good'),
('The Wild Gentlemen'),
('Salt Castle Studio'),
('Ajay Arora'),
('Quarantine Interactive'),
('Corfe83'),
('RAWR Lab'),
('Phantom Projekts'),
('Crimsonite Games'),
('ININ Games'),
('Runes of Mystery'),
('KangarooUnderlord'),
('Artur Berkowski Berobasket'),
('Tokyo Cowboys'),
('Wallace Lovecraft'),
('Male Doll'),
('Vercidium'),
('Bliss Games'),
('Northward Games'),
('Endurance Solutions L.L.C.'),
('Gamatron'),
('storkyproduct.'),
('PeriScope Game'),
('Yayapipi Studio'),
('Electro Gamma'),
('OHM Games SAS'),
('Electronic Arts'),
('织女星'),
('Mario Murkl'),
('Humble Games'),
('HappyGames'),
('DarkDes Labs'),
('Creative Art Studio'),
('Jam3'),
('Kanonix'),
('Awe Interactive'),
('Star Mountain Studios'),
('Rockhopper Labs'),
('INFINITY BRIDGE'),
('Wired Productions'),
('838s Maniacs'),
('Marvel Comics'),
('Skuhataagyall dev'),
('Diwen Chen'),
('Bounding Box Software'),
('Simpals'),
('DWGScripts'),
('Artalasky'),
('kevinmakesstuff'),
('Woodpecker'),
('Skywalker HK'),
('VeryHardMemeGames'),
('1Button'),
('DK Studio'),
('Xennial Digital'),
('机械神狐教制作组'),
('NCsoft'),
('BANDAI NAMCO Entertainment Europe'),
('Veronika Fomina'),
('Rebel Camp Games'),
('Joy Way'),
('UMURO'),
('RealDreamVision'),
('Klode'),
('Bright Geek Technology Co'),
('Playgendary'),
('MGTD Games'),
('EpiXR Games UG'),
('Deep Silver'),
('ARES'),
('Ravesta Games'),
('Lewd Digital'),
('Petite Fleur Productions'),
('Bottled Galaxy'),
('Team Gingerbread Man'),
('mowu'),
('Nakana.io'),
('Oh, a Rock! Studios'),
('Invisible Ghost Studios'),
('Dragonflare Studios'),
('Gameguru Advertisement FZC'),
('Harmonix'),
('应龙互娱'),
('1Moby Studio'),
('SNDO'),
('Beetroot Lab'),
('旅人计划'),
('GoodVole'),
('Voonle'),
('TapHazard Games'),
('Strange Beat Games'),
('BAITIAN TECHNOLOGY'),
('Hosted Games'),
('Sandrine Lamour'),
('Bilal Ahmad'),
('gnomearc'),
('morescore studio'),
('Popcore'),
('FEDOS CHANNEL'),
('Wainstop Games'),
('Aerobox Games'),
('Thunder Sparrow'),
('Massive Damage'),
('Lesson of Passion'),
('William at Oxford'),
('NX Multiservicos Ltda ME'),
('Niteagle'),
('RadPirates'),
('Shroud Studios'),
('Fox_Sebby'),
('ImperiumGame'),
('Spire Studio'),
('Pineleaf Studio'),
('United Independent Entertainment'),
('Dalcomsoft'),
('KG Games'),
('Inside Studios'),
('SadSquare Studio'),
('Sagittaras Games'),
('Rewindapp'),
('Demios'),
('jitensyasougyou'),
('Genene Game'),
('Astragon'),
('DianDian Interactive Holding'),
('Nekki'),
('Essence Games'),
('Longxi Zhao'),
('Naka Teleeli'),
('Bezbro Games'),
('Nacon'),
('necotama'),
('BloodBrothers Studios'),
('T124 Studios'),
('TerpySauce'),
('One Secret Pseudo'),
('Truong Minh'),
('Funselektor Labs'),
('WhisperGames'),
('WINGLAY'),
('VRGal.net'),
('Pixel Kinematics'),
('Akupara Games'),
('The Polygon Loft'),
('SeaPuppy Studios'),
('VRT'),
('Forklift Studios'),
('InCiti GAMES'),
('KGS2019'),
('Crayz'),
('SUPER.COM'),
('Jetdogs Studios'),
('GOLDEN ROCK GAMES'),
('Sandor Berczi'),
('Pablo Barrón'),
('Focus Home Interactive'),
('Julián Palacios Gechtman'),
('PiMark Games'),
('颂 王'),
('Burak Er'),
('FarSight Studios'),
('Soner Altıncit'),
('White Hole'),
('GalaxyTrail'),
('Garage Games'),
('Umut Haznedar'),
('Zaster'),
('Leturs Labs'),
('TamTamGames'),
('brennfeu'),
('droqen'),
('Teaklab'),
('Swaying Girl'),
('hanseygames'),
('Larian Studios'),
('Agile Softworks'),
('Cosmocat'),
('ICNP'),
('NL Studio'),
('CooCooSqueaky'),
('WAIFU4u'),
('ShiraVN'),
('Nibb Studio'),
('ThuleanPanteon'),
('Dymchick1'),
('Louis Protano'),
('LINE Games'),
('Gesinimo Games'),
('Sven Kröber'),
('RockGame'),
('Archetype'),
('Hyperbolic'),
('Roley Games'),
('Nutaku Publishing'),
('Gwydion LLyr Meredydd'),
('Phoenix Online Publishing'),
('Fractale'),
('思琪 沈'),
('KuKusFs Production'),
('Yahart'),
('Bekir Batuhan Celebi'),
('TheTallJS'),
('Geisha Tokyo'),
('Kalypso Media'),
('Atlus USA'),
('Kupaa Studios'),
('ShotX Studio'),
('Outright Games'),
('btf'),
('Skies Technologies'),
('Eversim'),
('Soiree Games'),
('Denis Sinner'),
('Survios'),
('Leoful'),
('Garage Heathen'),
('Ultimate Games'),
('Renecade'),
('Lucid Dreams Studio'),
('Llama Softworks'),
('Take Toad'),
('Torture Star Video'),
('AdroVGames'),
('GameFirst'),
('Anamik Majumdar'),
('Overaction Game Studio'),
('CodeJungle'),
('Somber Pixel'),
('Turquoise Revival Games'),
('Boogygames Studios'),
('Robert Hendry Games'),
('Nightdive Studios'),
('Appxplore'),
('Rising Star Games'),
('Adem KAYIRCI'),
('EYEFRONT'),
('Blind Monkey Games'),
('Warrior General Games'),
('Devolver Digital'),
('Cinesco'),
('Brandtner'),
('Average Games'),
('QuaranTime Games'),
('bhungry'),
('Millenium Games'),
('WHITE TIGERS Games'),
('Materik'),
('Blekoh'),
('Sceptical Orange'),
('AIKA ISHIZAWA'),
('Sum Co.'),
('ibleStudio'),
('橙光游戏'),
('Nerdvision Games'),
('Marvelous USA'),
('Gamejam Co.'),
('DU&I'),
('Pillow Castle'),
('Innersloth'),
('Whitethorn Digital'),
('Rename Studio'),
('Never Knows Best'),
('Vitok'),
('Thadius'),
('Opala Project'),
('Infini-Brain'),
('ThiGames'),
('GAMESWORD CO'),
('Unboxed Games'),
('Jack LaLonde'),
('2K Games'),
('MATER'),
('SeasonBeanTeam'),
('Noah Jaxon'),
('Alien Intelligence UAB'),
('Navalni Entertainment'),
('Ruben Pecellin'),
('Nicolas Meyssonnier'),
('winknowsgames'),
('JC Tinkers'),
('Studio Inkyfox'),
('Ziggurat Interactive'),
('Axis Games'),
('MINO ENTERTAINMENT'),
('NipoBox Publishing'),
('Everywear Games Oy'),
('Ludia'),
('Magno Borges Ladeira Filho'),
('TinyHat Studios'),
('Bulk Dominoes'),
('Techfragout'),
('Aurimas Drungilas'),
('Atahan Öztürk'),
('Shatterproof'),
('Wirlwith'),
('YOUZU SINGAPORE PTE'),
('Pyrebug Studios'),
('BaleYc Studios'),
('One Man Behind'),
('Crystal Game Works'),
('GOD'),
('Deen Games'),
('Aasura Project'),
('Steam'),
('Roberts Arts'),
('LIKE'),
('Kenshin Game Studio'),
('Knuckle Cracker'),
('Gnelf'),
('ComonGames'),
('Coffee Studio'),
('VIGAFUN VIET NAM COMPANY'),
('M3K4 Studio'),
('Piko Island Studios'),
('Microids Life'),
('Ateliér Duchů'),
('430Games'),
('王小波'),
('Neoclassic Games'),
('LUCAS A. FERNANDEZ'),
('myTrueSound'),
('Paulo Robson Allonso'),
('Lasse Zacho Malver'),
('THE NOVELLUS GROUP'),
('Flying Islands Team'),
('Santaworks'),
('nextjen'),
('Exalted Guy Interactive'),
('Virtuous VR Gaming'),
('THQ Nordic'),
('Anl0wér'),
('Dnovel'),
('AR-BRIDGE'),
('Rokyte Studio'),
('Eremite Games'),
('Spiral Digit'),
('AnAppleChurros'),
('GameMill Entertainment'),
('Novamanga Technology Co'),
('Stawberry Field'),
('Mighty Fox Studio'),
('Mister Morris Games'),
('Skunkape Games'),
('Bucksoft91'),
('RedZone Studios'),
('LIN GAN'),
('Orakga'),
('Reanimate Games'),
('Elf Games'),
('Giant Scam Industries'),
('480 Games'),
('Boomzap'),
('EDanDan Studio'),
('Soccer Manager'),
('mc2games'),
('Indigo Arts'),
('SVSdGAMEs'),
('QTArts'),
('TlpProject'),
('Games Operators'),
('AlikArt'),
('SKY HOUR WORKS'),
('Critical Bliss'),
('Herbert Lin'),
('Alamo Drafthouse Cinemas'),
('JTA Games'),
('Driple'),
('GameVille Studio'),
('Edward Petrak'),
('VirtexUniverse'),
('Honey Games'),
('Project Anthem'),
('Beep Beep'),
('Blue.Owl Game Studio'),
('Pine Drake Games'),
('X.D. Network'),
('Wave Light Games'),
('Kurumi Works'),
('Sector D2'),
('成都盟布克科技有限公司'),
('Futureplay Oy'),
('Plutoneus'),
('Dimension19'),
('Josh Larsen'),
('Studio Pareidolia Limited Liability Company'),
('Eutiquiano'),
('Ludicrous Games'),
('Konami'),
('CreativeForge Games'),
('Channel 7 Software'),
('やせいの工房'),
('Porter Zach'),
('XTANK'),
('Space River'),
('Hajime Doujin Circle'),
('Hyperstrange'),
('ComVice Games'),
('BananaChu Team'),
('Ant Design Games'),
('CrazyLoner'),
('Adknown'),
('Haci Bayhan'),
('Xbox Game Studios'),
('Renderise'),
('TinkerTyler'),
('七彩绘色游戏'),
('Guangzhou DiShiTian Software Company'),
('Corfaisus'),
('Rogue Games'),
('LoongCrown'),
('Boombox Games'),
('Jarze Games'),
('Binx.tv'),
('Tranquility games'),
('SimpleBit Studios ApS'),
('Michael Rfdshir'),
('Nokona Studios'),
('Tim Rachor'),
('Flixy'),
('Kalypso'),
('Choice of Games'),
('Pix Arts'),
('Fox'),
('Soviet Games'),
('Pew Times Three'),
('Owlnight'),
('Zin Games'),
('栋熙 黄'),
('Me First Games'),
('CyberStep'),
('EDO'),
('y2工作室'),
('NanningsGames'),
('DIG Publishing'),
('Jakob de Laval'),
('The Lazy Summer'),
('Retro Gears'),
('DEVGEIM, OOO'),
('Siarhei Belyahou'),
('Highrise Software'),
('Stone Baked Games'),
('Skonec Entertainment'),
('木秀于林'),
('Level up'),
('Niko Belik'),
('AHA MOMENT'),
('Young Phoenix Co'),
('leimonya'),
('ParadoxInteractive'),
('Free Reign Entertainment'),
('Pollapee Sroysuwan'),
('Bad Days Game Studios'),
('Ibrahim sofan'),
('AGM PLAYISM'),
('LunchHouse Software'),
('RealMono'),
('Joey Cook'),
('DillyFrame'),
('Louka Lemire'),
('Aksys Games Localization'),
('Project Tranquil'),
('MetalAdlerStudio'),
('se game'),
('zhang yue'),
('仙境传说'),
('WIREGAMES'),
('Iphigenia Games'),
('Ben Fredericks'),
('Broken Bunny Studios'),
('New Blood Interactive'),
('Studio 9.7'),
('Srio Studio'),
('ADHD GAMES'),
('Green Man Gaming Publishing'),
('内部の開発者'),
('BDT Digital'),
('Zordix Publishing'),
('Hentai Room'),
('Ragonsoft'),
('OTAKU Plan'),
('guang zhou xi pu wang luo ke ji you xian gong si'),
('AI GAMES FZ'),
('Disafter Games'),
('Tepes Ovidiu'),
('Novel Creatures'),
('Leocesar3D Productions'),
('pengjianNiu'),
('Techland Publishing'),
('Houndpicked Games'),
('Deertwig Studio'),
('Colorgrave'),
('Limited Run Games'),
('Zu Digital'),
('深圳市梦玩网络科技有限公司'),
('Playsaurus'),
('Anxiety Monster'),
('Proletariat'),
('ZangGames'),
('Zeinaru'),
('Stefounix'),
('Crystice Softworks'),
('Fubenalvo'),
('Ryan_Carlos'),
('Toplitz Productions'),
('Tilenauts'),
('Potato Chip With Onion Dip'),
('RK'),
('Leonardo P. D.'),
('Big Sugar'),
('Kyle Smith'),
('Digital Fox'),
('Rothman'),
('WayForward'),
('DEFANG LI'),
('Anden studios'),
('Trinity Project'),
('Tatem Games'),
('Retsa Games'),
('HypeTrain Digital'),
('Ricardo Alonso Pina'),
('Vantan Game Academy Tokyo'),
('Orube Game Studio'),
('继刚 陈'),
('Grenoble Interactive'),
('Airem'),
('Outfit7'),
('Cerberus Interactive'),
('Jackbox Games'),
('BJ Studio'),
('Cyber Keks'),
('FreeAnimals_Software'),
('Mi-Clos Studio'),
('Zilong Game'),
('orange'),
('Elena Titarenko'),
('Schell Games'),
('Triple Cyclone'),
('Singleton Foundation for Financial Literacy and Entrepreneurship'),
('Gokhan Sipahi'),
('D3 PUBLISHER'),
('寒蟬'),
('Zachtronics'),
('10mg'),
('Goblinz Studio'),
('Robbie And James'),
('Team17 Digital'),
('Firebrand Games'),
('Oath'),
('Blue Spot Games'),
('Dogukan Nurbige'),
('Creature-ations'),
('GREMORY GAMES'),
('Alawar Entertainment'),
('KIMIDORI SOFT'),
('Randumb Studios'),
('Limitcore.studio'),
('Brandon Adams'),
('Ravenhood Games'),
('Hentai Babe'),
('KESOFTGAMES'),
('me.mento XR interactive'),
('2>'),
('Quest Games'),
('Crisp App Studio'),
('Other Half Brewing Co.'),
('ROG STUDIOS'),
('Growing Seed Games'),
('Fuzhou Battle Game Information Technology Co'),
('TallRoad Studio'),
('Sweet Games'),
('Monster Games'),
('indie_games_studio'),
('S H B studio'),
('Magic Dragon Studios'),
('Bomjman Games'),
('sealMedia'),
('Vu Phan'),
('Curve Digital'),
('lightUP'),
('Inkle'),
('Arsi "Hakita" Patala'),
('Maple Whispering'),
('Lightning Games'),
('スタジオしまづ'),
('TooIzzi Games'),
('Pumpkin Head Studio'),
('Nifty Productions'),
('DreamTeam Mobile'),
('Heart Art Games'),
('Ziggurat'),
('RootSerious'),
('Strife AI'),
('Team Phoenix'),
('Marmalade Game Studio'),
('derevotyan'),
('Toge Productions'),
('Lyrical Games'),
('Crescent Moon Games'),
('ACE ACADEMY TEKNOLOJI ANONIM SIRKETI'),
('Haydee Interactive'),
('Joseph Murray'),
('斗罗大陆'),
('Raskal Games'),
('Mirrorsoft'),
('Exa_Inc'),
('Dark Beast Game'),
('SPIDERWORKS'),
('Perfect World Entertainment'),
('Bee Creative Games'),
('HIGGS TECHNOLOGY CO'),
('Tadeusz Lorkowski'),
('VR A&B'),
('8Floor'),
('Christoffer Tornell'),
('Sørb'),
('IL YA'),
('Zhi Rao'),
('Maybe Later Games'),
('Matthew Davis'),
('Carl Oberg'),
('Boke Technology Company'),
('Idle Games'),
('Chiodo Studios'),
('Private Division'),
('SHANHAI GAME STUDIO'),
('Kyle Muntz'),
('WitPOP'),
('South Gale'),
('PixelInd'),
('Egghead Interactive'),
('Jan Pielesiak'),
('NoraPerikaProject'),
('Greene Rapture'),
('Guerilla Media'),
('Centicerise Productions'),
('Assemble Entertainment'),
('CthuluPup Studios'),
('Pete Wilkins'),
('Apogee Software'),
('Goutham Krishnan Narayanswamy'),
('Lightspeed Design'),
('KEMCO'),
('TapNation'),
('Crytek'),
('NoNuclearWar'),
('凯峰 胡'),
('Anton Pauli'),
('9xgame'),
('ByVal Games'),
('inkakamu'),
('Jason Dale Swisher'),
('秋鼠'),
('나대는나'),
('Enhance'),
('Maximum Games'),
('ReAllis'),
('Ruben Alcañiz'),
('DTDA Games'),
('ScGame'),
('Hamster Team'),
('HOLOBOO LDA'),
('Kairosoft'),
('Ashnell Studios'),
('Dr. Linch'),
('Auroch Digital'),
('desigNULL'),
('AlexandrandRoman'),
('Ilya Gubin'),
('GoGallop Studios'),
('Modern Konzultacios'),
('UG Virtual Reality Technology Co.,Ltd.'),
('Pickle Drugs'),
('MyoungJang Games'),
('BlueFront'),
('SosiskaGames'),
('Moon Pub Games'),
('2210.io'),
('Slippy Floor'),
('Adrian McPhee'),
('Matthias Joost'),
('Tap4Fun'),
('Oneirolith'),
('inveshemin'),
('Plug In Digital'),
('Big Fish Games'),
('CritoGames'),
('Noio'),
('Fabio Cunha'),
('PotionPlayer'),
('Vladislav Castillo Gonzalez'),
('Fiction Fundation'),
('ThroneLab'),
('Wholetone Games'),
('Dream Reality Interactive'),
('敏敏 管'),
('Anatoliy Loginovskikh'),
('Cheese Games'),
('Individual'),
('GG Undroid Games'),
('Breakfast Games'),
('Alda Games'),
('ONESOFT GLOBAL PTE'),
('Inverse Game'),
('Jolly Theory'),
('Coloring puzzle games'),
('Eternal Night Studios'),
('HH-Games'),
('Button Bash Games'),
('Oddball Games'),
('LFC Multimedia'),
('2MEDYA'),
('gigantumgames'),
('Breakthrough Gaming'),
('Muhammad Asad Imran'),
('Bazookafriend'),
('指尖游道'),
('TechnoBrain'),
('Virtual and Physical Media Integration Association of Taiwan'),
('DMMD Team'),
('PanGuoJun'),
('IR Studio'),
('Khiem Nguyen'),
('Silver Cat Studios'),
('Ignition Publishing'),
('Talpel_games'),
('ABIGAMES PTE'),
('room6'),
('Dharker Studio'),
('Capriccio'),
('Nurcan Acar'),
('Vadim Slyusarev'),
('Crazysoft'),
('Little Black Book Entertainment'),
('樂磚Joy Brick'),
('AppTout'),
('Netmarble'),
('The Indie Accord'),
('MARC LEJEUNE'),
('Viroid Games'),
('Exxit'),
('夜葬半歌'),
('Onemangames'),
('UDevLemon'),
('Hong Kong Mingpei Trade Co'),
('Rooftop Panda'),
('TRANSLIMIT'),
('Tacklebox Productions'),
('toR Studio'),
('KONEKO'),
('Hook Games'),
('eagleclawgames'),
('ZPLAY (HK) TECHNOLOGY CO'),
('Studio Guts'),
('Colin Lane Games'),
('Arcade Distillery'),
('Tankafide Studios'),
('Carey White'),
('FlapStar'),
('505 Games'),
('Clike'),
('Cowboy Studio'),
('SHOPSOFT'),
('Kinetic Games'),
('WRF Studios'),
('chi'),
('Shaikonina Games'),
('KK Softworks'),
('Elephant Arts'),
('SLIDDES'),
('Gagonfe'),
('Seito Games'),
('Bithell Games'),
('rai'),
('Pieslice Productions'),
('Activison'),
('A Creative Endeavor'),
('Epicrone Technology'),
('Purple Jam'),
('Indie Games Publisher'),
('NEXT Studios'),
('Vector X Studios'),
('Snail Games USA'),
('MePlayItOnline'),
('Dromedary Games'),
('Hidden Achievement'),
('Rodrigo Oak'),
('Uken'),
('Riccardo Caprari'),
('Scumhead'),
('Black apple'),
('Strategy First'),
('Dhood Productions'),
('Хомяк Entertainment'),
('Ghostbutter'),
('The Quantum Astrophysicists Guild'),
('Kitfox Games'),
('Gunslinger Studios'),
('Keydare Project'),
('hede'),
('CyberCry Creators'),
('OutOfTheBit'),
('Lucky Games'),
('Ayatsuji_San'),
('CUBE GAMES YAZILIM SANAYI TICARET LIMITED SIRKETI'),
('Douze Dixièmes'),
('Mikkel Christiansen'),
('Magyu Studio'),
('Pujia8 Studio'),
('Ginger Dansler'),
('Nyanco Channel'),
('Block Games'),
('Wreck Tangle Games'),
('GefestGames'),
('Feel Good OPG'),
('Works In Theory'),
('Netease Games'),
('Big Rook Games'),
('TYPEX'),
('森の中の猫の小屋'),
('Tuning Mania'),
('yokaze'),
('Brett Schlereth'),
('Bluish-Green Games'),
('Tree Men Games OY'),
('Stracos'),
('Distinctive Developments'),
('Lateral Games'),
('Goat Co'),
('Atthus Games'),
('RJ Studio'),
('Michael Hall'),
('Red Limb Studio'),
('Vladislav Khorev'),
('V-RShop'),
('Falcão Caçador'),
('CARHAY Interactive'),
('Patrick Milholland'),
('ustwo games'),
('Badru'),
('East2West Games'),
('ProperBostin Interactive'),
('Venushja Games'),
('Ani4Bio Animated'),
('Dream Engine'),
('Sokpop Collective'),
('MK工作室'),
('Amira Zaki'),
('PeopleFun'),
('1001 Studio'),
('Brazen Legions'),
('Mad1 Games'),
('World of Legends'),
('H-GAME'),
('Blowfish Studios'),
('Frozen Helm'),
('Vivid Games'),
('FireFly Studios'),
('Pixel Games UK'),
('Quack Quack Games'),
('Gamera Game'),
('Jean-Baptiste de Clerfayt'),
('Aerosoft'),
('Asmodee Digital'),
('Exhibyte'),
('Drunk Robot'),
('StellarXiela'),
('M byrne'),
('Red Triangle Games'),
('Axyos Games'),
('SlifkerGames'),
('Revolver Nine'),
('WAY2BIT'),
('DarkStone Digital'),
('RP.Games'),
('BVRgames'),
('YOUZU (SINGAPORE) PTE'),
('ELENA PILIEVA'),
('Glass Heart Games'),
('Samuka Gomes'),
('MAD Studio'),
('Jinny Lab'),
('Benjamin Dressler'),
('SypherZent'),
('Glass Kettle Games'),
('AmagSwag Games'),
('Fancy Rainbow Productions'),
('Samer Khatib'),
('Lucky King Studio'),
('W van der Deijl'),
('Snkl Studio'),
('Black Tower Entertainment'),
('JinDing Chen'),
('КиКо'),
('Mechadonk Media'),
('.ToNg'),
('GuCubeStudio'),
('Sushi_soft'),
('VRstudios'),
('GreenLeaf Studios'),
('Kask Daxxe'),
('Atomic Sun Games'),
('Choloco'),
('Calin Ardelean'),
('Do Dinh Tho'),
('小海洋 MiniSea'),
('Hong Kong Bao Chuan Software Technology'),
('Draknek'),
('Adult Swim Games'),
('HandyGames'),
('CAIO FLAVIO'),
('Portal Games sp zoo'),
('Mustafa Mahmood'),
('Codemasters'),
('Jaroslav Patočka'),
('Gamer CDC'),
('CARAMEL COLUMN'),
('Halfbrick'),
('Gearbox Publishing'),
('oneLegNinja'),
('Individual Software'),
('oneP'),
('WickedSorceress'),
('Sinned Games'),
('EscapeVr.studio'),
('Ertal Games'),
('James'),
('Digital Things Sociedad Limitada'),
('Quite Good'),
('clover games'),
('TCHOW'),
('BlackHawk Games'),
('ITN NETWORKS'),
('Markus Kramer'),
('Chris Hanna'),
('Big Blue Bubble'),
('James Horn'),
('Minimol Games'),
('Tuxedo Labs'),
('LearnDistrict'),
('lilli'),
('Neon Play'),
('SeedWall'),
('Avalon Digital'),
('幻梦游戏'),
('P&P Games Studio'),
('Corva Nocta'),
('Games For Girls OÜ'),
('Interabang Entertainment'),
('HUNTERS'),
('Tenami'),
('Puppet Combo'),
('OLD GUARD GAMES'),
('9255'),
('Tornado Games'),
('USANIK'),
('Marjupi Games'),
('Horrible Guild'),
('Zordix'),
('Spike Chunsoft Co'),
('SeedBolt Studios'),
('Lantana Games'),
('斗罗'),
('Snow Run Games'),
('希瓦网络'),
('Niño Emprendedor'),
('MASOMO'),
('SOFTSTAR TECHNOLOGY (SHANGHAI) CO'),
('Infinite State Games'),
('SPACE COCKROACH CO.,LIMITED'),
('乐信游戏'),
('Octo Gaming'),
('BYCODEC TEKNOLOJI LIMITED SIRKETI'),
('Luci Entertainment'),
('Versus Studio'),
('Vamos a Desarrollar con Tokio S.A de C.V'),
('NEOWIZ'),
('Lozange Lab'),
('MY TOWN GAMES'),
('302 GAMES'),
('M3M Games'),
('Kodo Linija'),
('KOEI TECMO GAMES CO'),
('Mildly Professional'),
('LUCKY TYCOON STUDIO CO.,LIMITED'),
('The Incubator'),
('Ben Shattock'),
('TumbleweedGameDesign'),
('Kidding st.'),
('Josyan'),
('Alexander Voidoc'),
('Alexey Furman'),
('ESAT'),
('N3TWORK'),
('VISON STUDIOS'),
('Meteorbyte Studios'),
('Nolla Games'),
('myni'),
('Fowl Machinations'),
('Refract Games'),
('Dennel Cake'),
('Wampee'),
('Rémi Adriano'),
('Bluestial Games'),
('Roger Pollard'),
('Bloober Team NA'),
('Andrew Tebbe'),
('Mossmouth'),
('ZhangYuan Mobile Co'),
('Orbital Express'),
('SYMBOLICA'),
('Red Rider'),
('toOrock'),
('Voodoo'),
('Nitro Games Oyj'),
('MaGames'),
('Siyuan Studio'),
('HOBIBOX'),
('Miroslav Bago'),
('Aldorlea Games'),
('Big Cat Rescue'),
('Shared Dreams Studios'),
('Cyan Worlds'),
('Dayami Somar Rivera'),
('Royce Charles Fernandes'),
('HONGKONG BEPIC TECHNOLOGY CO.,LIMITED'),
('Glory Star'),
('Twice Different'),
('あうとさいど'),
('Denoriks Entertainment'),
('Asca Studio'),
('Far Few Giants'),
('Mad Hook'),
('EASYBRAIN'),
('Amanotes Pte'),
('PageBoy'),
('Noldo');